import os

AUTH_CHANNEL = set(int(x) for x in os.environ.get("AUTH_CHANNEL","YOUR CHAT ID GROUP OR PERSONAL HERE").split())  #CHAT ID HERE SEPERATE MULTIPLE ID WITH SPACE 
AUTH_CHANNEL = list(AUTH_CHANNEL)

TG_BOT_TOKEN = "YOUR BOT TOKEN HERE"
APP_ID =    #ENTER APP ID
API_HASH = "" #ENTER API HASH
MAINPATH ="S:/" #ENTER MOUNTED DIR PATH 
MOVIEPATH= "S:/MOVIE/" #Default Dont mind - SKIP
TVPATH = "S:/TVSHOW/" #Default Dont mind - SKIP
REMOTE_NAME ="REMOTE:" #Exmpl => REMOTE_NAME ="Arthur:BLACKPEARL/"
#ENTER REMOTE PATH U MOUNTED
#IF YOU MOUNT REMOTE: THEN PUT HERE THE SAME
#IF YOU MOUNTED REMOTE:MOVIE USE REMOTE:MOVIE/ HERE

OMDB_API = "" #KEY FROM OMDB
sleeptime= 40 #IF OMDB FAILS TO GRAB AUTOMATICALLY FROM FILENAME BOT ASKS IMDB ,THIS TIME IS THE WAITING TIME IN SECONDS
TMDB_API ="" #KEY FROM TMDB
